In [1]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

# --- Basics of TensorFlow and Tensors ---
print("--- Tensors ---")

a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

print("Tensor A:", a)
print("Tensor B:", b)
print("Addition:", tf.add(a, b))
print("Matrix Multiplication:", tf.matmul(a, b))

--- Tensors ---
Tensor A: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Tensor B: tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)
Addition: tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Matrix Multiplication: tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [2]:
# --- Creating and Running Computational Graphs ---
print("\n--- Computational Graph ---")

@tf.function
def simple_graph(x, y):
    return tf.multiply(x, y) + tf.add(x, y)

x = tf.constant(3.0)
y = tf.constant(2.0)
result = simple_graph(x, y)
print("Graph Output:", result)


--- Computational Graph ---
Graph Output: tf.Tensor(11.0, shape=(), dtype=float32)


In [3]:
# --- Simple Neural Networks with TensorFlow ---
print("\n--- Simple Neural Network ---")

# Synthetic dataset (X: features, y: binary labels)
X = np.array([[0,0], [0,1], [1,0], [1,1]], dtype=np.float32)
y = np.array([[0], [1], [1], [0]], dtype=np.float32)  # XOR


--- Simple Neural Network ---


In [4]:
model = Sequential([
    Dense(4, activation='relu', input_shape=(2,)),
    Dense(1, activation='sigmoid')
])

d:\PERSONAL_PROJECTS\Genai_training_rag\rag_venv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [5]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 4)              │            12 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 17 (68.00 B)

 Trainable params: 17 (68.00 B)

 Non-trainable params: 0 (0.00 B)

In [6]:
model.fit(X, y, epochs=100, verbose=0)
loss, acc = model.evaluate(X, y, verbose=0)
print(f"Model Accuracy: {acc:.2f}")


Model Accuracy: 0.75


In [7]:
predictions = model.predict(X)
print("Predictions:\n", np.round(predictions))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 191ms/step
Predictions:
 [[0.]
 [0.]
 [1.]
 [0.]]
