In [1]:
# Day 6: Introduction to NumPy
# ----------------------------
import numpy as np

# 1. Creating Arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2], [3, 4]])
print("1D:", arr1)
print("2D:", arr2)

1D: [1 2 3]
2D: [[1 2]
 [3 4]]


In [2]:
# Create array with zeros/ones/empty
z = np.zeros((2, 3))
o = np.ones((3,))
e = np.empty((2, 2))
print("Zeros:", z)
print("Ones:", o)
print("Empty:", e)

Zeros: [[0. 0. 0.]
 [0. 0. 0.]]
Ones: [1. 1. 1.]
Empty: [[6.01347002e-154 1.64953213e+150]
 [8.70183202e+150 1.71437959e+161]]


In [3]:
# Range and linspace
r = np.arange(0, 10, 2)
l = np.linspace(0, 1, 5)
print("Arange:", r)
print("Linspace:", l)

Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]


In [4]:
# Identity matrix
i = np.eye(3)
print("Identity matrix:\n", i)

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
# Random array
rand_arr = np.random.rand(2, 3)
print("Random:", rand_arr)

Random: [[0.06079692 0.95349719 0.8651396 ]
 [0.69267061 0.38012063 0.22674754]]


In [6]:
# 2. Array Attributes
print("Shape:", arr2.shape)
print("Size:", arr2.size)
print("Data type:", arr2.dtype)


Shape: (2, 2)
Size: 4
Data type: int64


In [7]:
# 3. Indexing and Slicing
arr = np.array([10, 20, 30, 40, 50])
print("Element at 2nd index:", arr[2])
print("Slice 1:4:", arr[1:4])

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Element [1,2]:", matrix[1, 2])
print("Row 0:", matrix[0])
print("Col 1:", matrix[:, 1])

Element at 2nd index: 30
Slice 1:4: [20 30 40]
Element [1,2]: 6
Row 0: [1 2 3]
Col 1: [2 5]


In [8]:
# 4. Reshaping Arrays
flat = np.array([1, 2, 3, 4, 5, 6])
reshaped = flat.reshape((2, 3))
print("Reshaped:\n", reshaped)

# Flatten a matrix
print("Flatten:", reshaped.flatten())

Reshaped:
 [[1 2 3]
 [4 5 6]]
Flatten: [1 2 3 4 5 6]


In [9]:
# 5. Basic Operations
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print("Add:", x + y)
print("Multiply:", x * y)
print("Square:", x ** 2)
print("Comparison:", x > 1)

Add: [5 7 9]
Multiply: [ 4 10 18]
Square: [1 4 9]
Comparison: [False  True  True]


In [10]:
# Dot product
print("Dot product:", np.dot(x, y))

Dot product: 32


In [11]:
# 6. Broadcasting
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])
print("Broadcasted sum:\n", a + b)


Broadcasted sum:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


In [12]:
# 7. Vectorized Operations
arr = np.array([1, 2, 3, 4, 5])
print("Sine:", np.sin(arr))
print("Log:", np.log(arr))
print("Exp:", np.exp(arr))

Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Log: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Exp: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [13]:
# 8. Aggregations
print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Std Dev:", arr.std())
print("Min:", arr.min())
print("Max:", arr.max())
print("Cumsum:", arr.cumsum())

Sum: 15
Mean: 3.0
Std Dev: 1.4142135623730951
Min: 1
Max: 5
Cumsum: [ 1  3  6 10 15]


In [14]:
# 9. Axis-wise Operations
matrix = np.array([[1, 2], [3, 4]])
print("Sum by row:", matrix.sum(axis=1))
print("Sum by column:", matrix.sum(axis=0))


Sum by row: [3 7]
Sum by column: [4 6]


In [15]:
# 10. Copy vs View
original = np.array([1, 2, 3])
view = original[:]
copy = original.copy()
view[0] = 99
print("Original after view change:", original)
copy[1] = 88
print("Original after copy change:", original)

Original after view change: [99  2  3]
Original after copy change: [99  2  3]


In [16]:
# 11. Boolean Masking
arr = np.array([10, 15, 20, 25])
mask = arr > 15
print("Mask:", mask)
print("Filtered:", arr[mask])

Mask: [False False  True  True]
Filtered: [20 25]


In [17]:
# 12. Where condition
result = np.where(arr > 15, "High", "Low")
print("Where:", result)

Where: ['Low' 'Low' 'High' 'High']
