In [2]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6, 7], [8, 9, 10]])
C = np.dot(A, B)
print("Matrix Multiplication (2x2 * 2x3):")
print(C)


Matrix Multiplication (2x2 * 2x3):
[[21 24 27]
 [47 54 61]]


In [3]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A_transpose = np.transpose(A)
print("Matrix Transposition:")
print(A_transpose)


Matrix Transposition:
[[1 3 5]
 [2 4 6]]


In [4]:

A = np.array([[1, 2], [3, 4]])
determinant = np.linalg.det(A)
print("Matrix Determinant:")
print(determinant)


Matrix Determinant:
-2.0000000000000004


In [5]:
A = np.array([[1, 2], [3, 4]])
A_inv = np.linalg.inv(A)
print("Matrix Inversion:")
print(A_inv)


Matrix Inversion:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [6]:
A = np.array([[4, -2], [1, 1]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues and Eigenvectors:")
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
print(eigenvectors)


Eigenvalues and Eigenvectors:
Eigenvalues: [3. 2.]
Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [7]:
A = np.array([[1, 2], [3, 4], [5, 6]])
rank = np.linalg.matrix_rank(A)
print("Matrix Rank:")
print(rank)


Matrix Rank:
2


In [8]:
A = np.array([[3, 2], [1, 2]])
b = np.array([10, 8])
x = np.linalg.solve(A, b)
print("Solution to Ax = b:")
print(x)


Solution to Ax = b:
[1.  3.5]


In [9]:
random_float = np.random.random()
print("Random float between 0 and 1:", random_float)


Random float between 0 and 1: 0.7838518968138137


In [10]:
random_int = np.random.randint(1, 10)
print("Random integer between 1 and 10:", random_int)


Random integer between 1 and 10: 9


In [11]:
random_array = np.random.random((3, 3))
print("Random array (3x3):")
print(random_array)


Random array (3x3):
[[0.91999639 0.07855199 0.16765803]
 [0.6336616  0.16809624 0.85195773]
 [0.28276584 0.35201934 0.37688547]]


In [14]:
random_int_array = np.random.randint(1, 100, size=(4, 5))
print("Random integer array (4x5):")
print(random_int_array)


Random integer array (4x5):
[[27 29 72 47 36]
 [94 82 21 96 28]
 [ 1 73 68 30 82]
 [ 2 19 90 63 75]]


In [15]:
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print("Shuffled array:")
print(arr)


Shuffled array:
[3 2 4 5 1]


In [16]:
arr = np.array([1, 2, 3, 4, 5])
random_choice = np.random.choice(arr, size=3)
print("Random choice from array:")
print(random_choice)


Random choice from array:
[2 4 2]


In [17]:
data = np.random.randn(100)
mean = np.mean(data)
print("Mean of the data:", mean)


Mean of the data: -0.08909028035482425


In [18]:
median = np.median(data)
print("Median of the data:", median)


Median of the data: -0.1442302955302185


In [19]:
std_dev = np.std(data)
print("Standard Deviation of the data:", std_dev)


Standard Deviation of the data: 1.0004701754096181


In [20]:
variance = np.var(data)
print("Variance of the data:", variance)


Variance of the data: 1.000940571884152
